### ISSUE TITLE
Embedded videos do not show in closed accordions

### ISSUE THREAD

**Issue by chantichant** [philbuchanan/Accordion-Shortcodes#41] opened 2015-09-22 14:21 UTC
If an accordion is previously closed and a video is embedded inside it, upon opening the accordion, the video does not appear. If the accordion starts open, videos appear as expected.

**Comment by philbuchanan** [comment] 2015-09-24 01:29
I cannot reproduce this issue. When I place a variety of embedded videos in accordions, they appear as expected, even after repeated opening and closing of the accordion. Can you provide more details about what video you are trying to embed. A link to the page where it illustrates the issue would also be helpful.

**Comment by chantichant** [comment] 2015-10-07 20:56
Sorry for the late reply. Here is an example page https://helpdesk.lastpass.com/fill-form-basics/. In the accordion "Adding a Form Fill Profile" there is a youtube video embedded at the bottom of the accordion:

&nbsp;

<iframe src="//www.youtube.com/embed/pRZMoc0t_CU" width="640" height="360" frameborder="0" allowfullscreen="allowfullscreen"></iframe>

&nbsp;

Could it be our theme causing a conflict?

**Comment by philbuchanan** [comment] 2015-10-08 00:17
It very likely could be a theme or other plugin conflict. I tested the exact iframe and it works perfectly for me in a few different themes.

**Comment by chantichant** [comment] 2015-10-08 19:01
Thanks for taking a look. I found that putting videos in a tab will allow it to work, so its a pretty solid workaround for now. I'll play around with what we have. Feel free to close this one out. Thanks, again!

**Closed** 2015-10-08 20:19 UTC
Labels: bug, wontfix
